# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "72da450e4e3eead6f7b5d1e266d6d7c7"
application_url = "https://lap-electronic-yea-farm.trycloudflare.com"
embedded = true
name = "Reviews: Import & Display"
handle = "review-import-display"

[build]
include_config_on_deploy = true
dev_store_url = "devs00.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://lap-electronic-yea-farm.trycloudflare.com/auth/callback",
  "https://lap-electronic-yea-farm.trycloudflare.com/auth/shopify/callback",
  "https://lap-electronic-yea-farm.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
